name:                lasercutter
version:             0.1.0.0
github:              "isovector/lasercutter"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/lasercutter#readme>

dependencies:
- base >= 4.7 && < 5
- witherable
- selective
- profunctors

default-extensions:
- BangPatterns
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- GADTs
- ImplicitPrelude
- LambdaCase
- MonomorphismRestriction
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

benchmarks:
  lasercutter-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - lasercutter
    - criterion
    - scalpel
    - tagsoup
    - text
    - deepseq
    - containers

tests:
  lasercutter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lasercutter
    - recover-rtti
    - QuickCheck
    - checkers
    - containers
